
function(SetTargetMacroStd TARGET)
    if(MSVC)
        message(STATUS "Platform is Windows, Using MSVC Compiler Version ${MSVC_VERSION}")
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_WINDOWS=1)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_LINUX=0)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_MACOS=0)
    elseif(UNIX AND NOT APPLE AND NOT MSVC)
        message(STATUS "Platform is Linux, Using GCC Compiler Version ${CMAKE_CXX_COMPILER_VERSION}")
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_WINDOWS=0)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_LINUX=1)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_MACOS=0)
    elseif(APPLE)
        message(STATUS "Platform is MacOS, Using GCC Compiler Version ${CMAKE_CXX_COMPILER_VERSION}")
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_WINDOWS=0)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_LINUX=0)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_MACOS=1)
    else()
        message(WARNING "Unsupported platform")
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_WINDOWS=0)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_LINUX=0)
        target_compile_definitions(${TARGET} PRIVATE STRAND_PLATFORM_MACOS=0)
    endif()

    if(MSVC)
        message(STATUS "For Export Macros, Using MSVC Compiler Version ${MSVC_VERSION}")
        target_compile_definitions(${TARGET} PRIVATE EXPORT_STRAND_STD=__declspec\(dllexport\))
    elseif(GNUCXX)
        message(STATUS "For Export Macros, Using GCC Compiler Version ${CMAKE_CXX_COMPILER_VERSION}")
        target_compile_definitions(${TARGET} PRIVATE EXPORT_STRAND_STD=__attribute__\(\(visibility\(\"default\"\)\)\))
    else()
        message(WARNING "Unsupported compiler for export macros")
        target_compile_definitions(${TARGET} PRIVATE EXPORT_STRAND_STD=)
    endif()

    if(MSVC)
        message(STATUS "For Inline Macros, Using MSVC Compiler Version ${MSVC_VERSION}")
        target_compile_definitions(${TARGET} PUBLIC FORCEINLINE=__forceinline)
        target_compile_definitions(${TARGET} PUBLIC NOINLINE=__declspec\(noinline\))
        target_compile_definitions(${TARGET} PUBLIC INLINE=__inline)
    elseif(GNUCXX)
        message(STATUS "For Inline Macros, Using GCC Compiler Version ${CMAKE_CXX_COMPILER_VERSION}")
        target_compile_definitions(${TARGET} PUBLIC FORCEINLINE=__attribute__\(\(always_inline\)\) inline)
        target_compile_definitions(${TARGET} PUBLIC NOINLINE=__attribute__\(\(noinline\)\))
        target_compile_definitions(${TARGET} PUBLIC INLINE=inline)
    else()
        message(WARNING "Unsupported compiler for inline macros")
        target_compile_definitions(${TARGET} PUBLIC FORCEINLINE=)
        target_compile_definitions(${TARGET} PUBLIC NOINLINE=)
        target_compile_definitions(${TARGET} PUBLIC INLINE=)
    endif()

    if(MSVC)
        message(STATUS "For Nullptr Macros, Using MSVC Compiler Version ${MSVC_VERSION}")
        target_compile_definitions(${TARGET} PUBLIC NULLPTR=decltype\(nullptr\)\(\))
    elseif(GNUCXX)
        message(STATUS "For nullptr Macros, Using GCC Compiler Version ${CMAKE_CXX_COMPILER_VERSION}")
        target_compile_definitions(${TARGET} PUBLIC NULLPTR=nullptr)
    else()
        message(WARNING "Unsupported compiler for nullptr macros")
        target_compile_definitions(${TARGET} PUBLIC NULLPTR=)
    endif()
endfunction()